export const navLinks = [
    {
        id:"home",
        title:"Home"
    },
    {
        id:"portfolio",
        title:"Portfolio"
    },
    {
        id:"services",
        title:"Services"
    },
    {
        id:"pricing",
        title:"Pricing"
    },
    {
        id:"faq",
        title:"FAQ"
    }
];